// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCUgXsDTx6cIVGnlvjDwc-hO7Xtz4WykY',
    appId: '1:390195336238:web:813d417c41bb25895a3bbf',
    messagingSenderId: '390195336238',
    projectId: 'mynotes-njehu',
    authDomain: 'mynotes-njehu.firebaseapp.com',
    storageBucket: 'mynotes-njehu.appspot.com',
    measurementId: 'G-SFGGHD6S3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP-016Vlzuxk7OsBioSI4CNKDt9uYje9E',
    appId: '1:390195336238:android:f50235370d5c8c295a3bbf',
    messagingSenderId: '390195336238',
    projectId: 'mynotes-njehu',
    storageBucket: 'mynotes-njehu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiS-cGLWFgUdIcNlFZTs3evayPmymjO2I',
    appId: '1:390195336238:ios:3ad7f54e469340e65a3bbf',
    messagingSenderId: '390195336238',
    projectId: 'mynotes-njehu',
    storageBucket: 'mynotes-njehu.appspot.com',
    iosClientId: '390195336238-8koo0ihjnvk1v0lm6pii1pkf45bdq4qc.apps.googleusercontent.com',
    iosBundleId: 'com.monjepartners.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiS-cGLWFgUdIcNlFZTs3evayPmymjO2I',
    appId: '1:390195336238:ios:3ad7f54e469340e65a3bbf',
    messagingSenderId: '390195336238',
    projectId: 'mynotes-njehu',
    storageBucket: 'mynotes-njehu.appspot.com',
    iosClientId: '390195336238-8koo0ihjnvk1v0lm6pii1pkf45bdq4qc.apps.googleusercontent.com',
    iosBundleId: 'com.monjepartners.mynotes',
  );
}
